export function getAllMachines() {
    return [
        { id: 1, name: "Work Up", type: "normal", pp: 30, power: "-", accuracy: 101, description: "The user is roused, and its Attack and Sp. Atk stats increase." },
        { id: 2, name: "Dragon Claw", type: "dragon", pp: 15, power: 80, accuracy: 100, description: "The user slashes the target with huge sharp claws." },
        { id: 3, name: "Psyshock", type: "psychic", pp: 10, power: 80, accuracy: 100, description: "The user materializes an odd psychic wave to attack the target. This attack does physical damage."  },
        { id: 4, name: "Calm Mind", type: "psychic", pp: 20, power: "-", accuracy: 101, description: "The user quietly focuses its mind and calms its spirit to raise its Sp. Atk and Sp. Def stats." },
        { id: 5, name: "Roar", type: "noraml", pp: 20, power: "-", accuracy: 101, description: "The target is scared off, and a different Pokémon is dragged out. In the wild, this ends a battle against a single Pokémon." },
        { id: 6, name: "Toxic", type: "poison", pp: 10, power: "-", accuracy: 90, description: "A move that leaves the target badly poisoned. Its poison damage worsens every turn." },
        { id: 7, name: "Hail", type: "ice", pp: 10, power: "-", accuracy: 101, description: "The user summons a hailstorm lasting five turns. It damages all Pokémon except the Ice type." },
        { id: 8, name: "Bulk Up", type: "fighting", pp: 20, power: "-", accuracy: 101, description: "The user tenses its muscles to bulk up its body, raising both its Attack and Defense stats." },
        { id: 9, name: "Venoshock", type: "poison", pp: 10, power: 65, accuracy: 100, description: "The user drenches the target in a special poisonous liquid. This move's power is doubled if the target is poisoned." },
        { id: 10, name: "Hidden Power", type: "normal", pp: 15, power: 60, accuracy: 100, description: "A unique attack that varies in type depending on the Pokémon using it." },
        { id: 11, name: "Sunny Day", type: "fire", pp: 5, power: "-", accuracy: 101, description: "The user intensifies the sun for five turns, powering up Fire-type moves. It lowers the power of Water-type moves." },
        { id: 12, name: "Taunt" , type: "dark", pp: 20, power: "-", accuracy: 100, description: "The target is taunted into a rage that allows it to use only attack moves for three turns."},
        { id: 13, name: "Ice Beam", type: "ice", pp: 10, power: 90, accuracy: 100, description: "The target is struck with an icy-cold beam of energy. This may also leave the target frozen." },
        { id: 14, name: "Blizzard" , type: "ice", pp: 5, power: 110, accuracy: 70, description: "A howling blizzard is summoned to strike opposing Pokémon. This may also leave the opposing Pokémon frozen."},
        { id: 15, name: "Hyper Beam" , type: "normal", pp: 5, power: 150, accuracy: 90, description: "The target is attacked with a powerful beam. The user can't move on the next turn."},
        { id: 16, name: "Light Screen", type: "pyschic", pp: 30, power: "-", accuracy: 101, description: "A wondrous wall of light is put up to reduce damage from special attacks for five turns." },
        { id: 17, name: "Protect", type: "normal", pp: 10, power: "-", accuracy: 101, description: "Enables the user to evade all attacks. Its chance of failing rises if it is used in succession." },
        { id: 18, name: "Rain Dance", type: "water", pp: 5, power: "-", accuracy: 101, description: "The user summons a heavy rain that falls for five turns, powering up Water-type moves. It lowers the power of Fire-type moves." },
        { id: 19, name: "Roost", type: "flying", pp: 10, power: "-", accuracy: 101, description: "The user lands and rests its body. It restores the user's HP by up to half of its max HP." },
        { id: 20, name: "Safeguard" , type: "normal", pp: 25, power: "-", accuracy: 101, description: "The user creates a protective field that prevents status conditions for five turns."},
        { id: 21, name: "Frustration", type: "normal", pp: 20, power: "-", accuracy: 100, description: "This full-power attack grows more powerful the less the user likes its Trainer." },
        { id: 22, name: "Solar Beam" , type: "grass", pp: 10, power: 120, accuracy: 100, description: "In this two-turn attack, the user gathers light, then blasts a bundled beam on the next turn."},
        { id: 23, name: "Smack Down" , type: "rock", pp: 15, power: 50, accuracy: 100, description: "The user throws a stone or similar projectile to attack an opponent. A flying Pokémon will fall to the ground when it's hit."},
        { id: 24, name: "Thunderbolt", type: "electric", pp: 15, power: 90, accuracy: 100, description: "A strong electric blast crashes down on the target. This may also leave the target with paralysis." },
        { id: 25, name: "Thunder", type: "electric", pp: 10, power: 110, accuracy: 70, description: "A wicked thunderbolt is dropped on the target to inflict damage. This may also leave the target with paralysis." },
        { id: 26, name: "Earthquake" , type: "ground", pp: 10, power: 100, accuracy: 100, description: "The user sets off an earthquake that strikes every Pokémon around it."},
        { id: 27, name: "Return" , type: "normal", pp: 20, power: "-", accuracy: 100, description: "This full-power attack grows more powerful the more the user likes its Trainer."},
        { id: 28, name: "Leech Life" , type: "bug", pp: 10, power: 80, accuracy: 100, description: "The user drains the target's blood. The user's HP is restored by half the damage taken by the target."},
        { id: 29, name: "Psychic", type: "psychic", pp: 10, power: 90, accuracy: 100, description: "The target is hit by a strong telekinetic force. This may also lower the target's Sp. Def stat." },
        { id: 30, name: "Shadow Ball", type: "ghost", pp: 15, power: 80, accuracy: 100, description: "The user hurls a shadowy blob at the target. This may also lower the target's Sp. Def stat." },
        { id: 31, name: "Brick Break", type: "fighting", pp: 15, power: 75, accuracy: 100, description: "The user attacks with a swift chop. It can also break barriers, such as Light Screen and Reflect." },
        { id: 32, name: "Double Team", type: "normal", pp: 15, power: "-", accuracy: 101, description: "By moving rapidly, the user makes illusory copies of itself to raise its evasiveness." },
        { id: 33, name: "Reflect" , type: "pyschic", pp: 20, power: "-", accuracy: 101, description: "A wondrous wall of light is put up to reduce damage from physical attacks for five turns."},
        { id: 34, name: "Sludge Wave", type: "poison", pp: 10, power: 95, accuracy: 100, description: "The user strikes everything around it by swamping the area with a giant sludge wave. This may also poison those hit." },
        { id: 35, name: "Flamethrower" , type: "fire", pp: 15, power: 90, accuracy: 100, description: "The target is scorched with an intense blast of fire. This may also leave the target with a burn."},
        { id: 36, name: "Sludge Bomb", type: "poison", pp: 10, power: 90, accuracy: 100, description: "Unsanitary sludge is hurled at the target. This may also poison the target." },
        { id: 37, name: "Sandstorm" , type: "rock", pp: 10, power: "-", accuracy: 101, description: "A five-turn sandstorm is summoned to hurt all combatants except the Rock, Ground, and Steel types. It raises the Sp. Def stat of Rock types."},
        { id: 38, name: "Fire Blast" , type: "fire", pp: 5, power: 110, accuracy: 85, description: "The target is attacked with an intense blast of all-consuming fire. This may also leave the target with a burn."},
        { id: 39, name: "Rock Tomb" , type: "rock", pp: 15, power: 60, accuracy: 95, description: "Boulders are hurled at the target. This also lowers the target's Speed stat by preventing its movement."},
        { id: 40, name: "Aerial Ace" , type: "flying", pp: 20, power: 60, accuracy: 101, description: "The user confounds the target with speed, then slashes. This attack never misses."},
        { id: 41, name: "Torment", type: "dark", pp: 15, power: "-", accuracy: 101, description: "The user torments and enrages the target, making it incapable of using the same move twice in a row." },
        { id: 42, name: "Facade" , type: "normal", pp: 20, power: 70, accuracy: 100, description: "This attack move doubles its power if the user is poisoned, burned, or paralyzed."},
        { id: 43, name: "Flame Charge", type: "fire", pp: 20, power: 50, accuracy: 100, description: "Cloaking itself in flame, the user attacks. Then, building up more power, the user raises its Speed stat." },
        { id: 44, name: "Rest" , type: "psychic", pp: 10, power: "-", accuracy: 101, description: "The user goes to sleep for two turns. This fully restores the user's HP and heals any status conditions."},
        { id: 45, name: "Attract", type: "normal", pp: 15, power: "-", accuracy: 100, description: "If it is the opposite gender of the user, the target becomes infatuated and less likely to attack." },
        { id: 46, name: "Thief" , type: "dark", pp: 25, power: 60, accuracy: 100, description: "The user attacks and steals the target's held item simultaneously. The user can't steal anything if it already holds an item."},
        { id: 47, name: "Low Sweep" , type: "fighting", pp: 20, power: 65, accuracy: 100, description: "The user makes a swift attack on the target's legs, which lowers the target's Speed stat."},
        { id: 48, name: "Round" , type: "normal", pp: 15, power: 60, accuracy: 100, description: "The user attacks the target with a song. Others can join in the Round to increase the power of the attack."},
        { id: 49, name: "Echoed Voice", type: "normal", pp: 15, power: 40, accuracy: 100, description: "The user attacks the target with an echoing voice. If this move is used every turn, its power is increased." },
        { id: 50, name: "Overheat", type: "dragon", pp: 5, power: 130, accuracy: 90, description: "The user attacks the target at full power. The attack's recoil harshly lowers the user's Sp. Atk stat." }
        // { id: 51, name: "Steel Wing" },
        // { id: 52, name: "Focus Blast" },
        // { id: 53, name: "Energy Ball" },
        // { id: 54, name: "False Swipe" },
        // { id: 55, name: "Scald" },
        // { id: 56, name: "Fling" },
        // { id: 57, name: "Charge Beam" },
        // { id: 58, name: "Sky Drop" },
        // { id: 59, name: "Brutal Swing" },
        // { id: 60, name: "Quash" },
        // { id: 61, name: "Will-O-Wisp" },
        // { id: 62, name: "Acrobatics" },
        // { id: 63, name: "Embargo" },
        // { id: 64, name: "Explosion" },
        // { id: 65, name: "Shadow Claw" },
        // { id: 66, name: "Payback" },
        // { id: 67, name: "Smart Strike" },
        // { id: 68, name: "Giga Impact" },
        // { id: 69, name: "Rock Polish" },
        // { id: 70, name: "Aurora Veil" },
        // { id: 71, name: "Stone Edge" },
        // { id: 72, name: "Volt Switch" },
        // { id: 73, name: "Thunder Wave" },
        // { id: 74, name: "Gyro Ball" },
        // { id: 75, name: "Swords Dance" },
        // { id: 76, name: "Fly" },
        // { id: 77, name: "Psych Up" },
        // { id: 78, name: "Bulldoze" },
        // { id: 79, name: "Frost Breath" },
        // { id: 80, name: "Rock Slide" },
        // { id: 81, name: "X-Scissor" },
        // { id: 82, name: "Dragon Tail" },
        // { id: 83, name: "Infestation" },
        // { id: 84, name: "Poison Jab" },
        // { id: 85, name: "Dream Eater" },
        // { id: 86, name: "Grass Knot" },
        // { id: 87, name: "Swagger" },
        // { id: 88, name: "Sleep Talk" },
        // { id: 89, name: "U-turn" },
        // { id: 90, name: "Substitute" },
        // { id: 91, name: "Flash Cannon" },
        // { id: 92, name: "Trick Room" },
        // { id: 93, name: "Wild Charge" },
        // { id: 94, name: "Surf" },
        // { id: 95, name: "Snarl" },
        // { id: 96, name: "Nature Power" },
        // { id: 97, name: "Dark Pulse" },
        // { id: 98, name: "Waterfall" },
        // { id: 99, name: "Dazzling Gleam" },
        // { id: 100, name: "Confide" }
    ]
}

export function getMachineFromName(name){
    const data = getAllMachines();
    const target = data.find(el => {
        return el.name === name
    });
    return target;
}